### PR TITLE
Add `MPI_` prefix to internal status field

### PR DESCRIPTION
**Pull request by eschnett**
We're just being extra careful here.

### CODE REVIEW

**Comment by jeffhammond** [comment]
I don't understand how this matters. No one should ever touch this. How can the name be significant?

**Comment by eschnett** [comment]
The calling code might do a `#define internal 42`. If we stick with using an `MPI_` prefix for everything then we're safe.

See e.g. `struct rusage` where the fields all have an `ru_` prefix.

**Comment by jeffhammond** [comment]
Wouldn't it be better to use something that starts with __ then since that's reserved by the C language?

**Comment by dalcinl** [comment]
* As C reserves identifiers starting with _ and continuing with an uppercase char, we would be breaking the rules and a picky compiler could potentially generate a warning/error, and we do not want that. 
* MPI has already reserved both the `MPI_` and `mpi_` prefixes (page 24), therefore I don't have too many arguments to not use one of those here and pick something different. Perhaps lower case `mpi_`  would be more appropriate here?

Caveat: `MPI_internal` does not convey properly the "private" intention for the field. Using `_mpi_private` would work better in this case as  `_<lowercase...>` is not reserved by C, but MPI has not so far reserved lowercase `_mpi_` starting with underscore.

**Review by dalcinl — APPROVED** [review]

**Pull request merged**
